services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./store.db:/app/store.db

  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/provisioning:/etc/grafana/provisioning
      - ./monitoring/Store Service Dashboard.json:/etc/grafana/dashboards/store_service_dashboard.json
    depends_on:
      - prometheus

volumes:
  grafana_data:
