services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./store.db:/app/store.db
    env_file:
      - .env
    labels:
      - "logging=promtail"
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    ports:
      - "4318:4318"
      - "3200:3200"
    volumes:
      - ./monitoring/tempo.yml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    command: -config.file=/etc/tempo.yaml

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/provisioning:/etc/grafana/provisioning
      - ./monitoring/Store Service Dashboard.json:/etc/grafana/dashboards/store_service_dashboard.json
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  grafana_data:
  loki_data:
  tempo_data: