{
 "title": "Store Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Orders Created (last 1h)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(store_orders_created_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Insufficient Stock Rejections (last 1h)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(store_insufficient_stock_total[1h])) by (product_id))",
     "legendFormat": "product {{product_id}}"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler, method)",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  }
 ]
}